language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install git+https://github.com/RasaHQ/rasa_core.git@sdk_plans
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "ASDF"
